PRODUCT_LABELS = {
    "lead": "plomo",
    "coca": "planta misteriosa",
    "iron": "hierro",
    "fish": "pescado",
    "livestock": "ganado",
    "grain": "grano",
    "limestone": "caliza",
    "lightAmmo": "munición ligera",
    "bread": "pan",
    "steel": "acero",
    "concrete": "hormigón",
    "ammo": "munición",
    "steak": "carne",
    "heavyAmmo": "munición pesada",
    "cocain": "píldora",
    "cookedFish": "pescado cocido",
    "case1": "caja",
}
